### ISSUE TITLE
Fix schedule error "blocks is not defined"

### ISSUE THREAD

**Issue by michaelgira23** [michaelgira23/MyMICDS-v2#28]
This error occasionally happens. Haven't looked into what circumstances this happens, but it do.

```
4|mymicds  | ReferenceError: blocks is not defined
4|mymicds  |     at asyncLib.parallel (/home/node/MyMICDS/MyMICDS-v2/src/libs/schedule.js:289:6)
4|mymicds  |     at /home/node/MyMICDS/MyMICDS-v2/node_modules/async/dist/async.js:3853:9
4|mymicds  |     at /home/node/MyMICDS/MyMICDS-v2/node_modules/async/dist/async.js:484:16
4|mymicds  |     at iterateeCallback (/home/node/MyMICDS/MyMICDS-v2/node_modules/async/dist/async.js:1013:24)
4|mymicds  |     at /home/node/MyMICDS/MyMICDS-v2/node_modules/async/dist/async.js:988:16
4|mymicds  |     at /home/node/MyMICDS/MyMICDS-v2/node_modules/async/dist/async.js:3850:13
4|mymicds  |     at apply (/home/node/MyMICDS/MyMICDS-v2/node_modules/async/dist/async.js:41:25)
4|mymicds  |     at /home/node/MyMICDS/MyMICDS-v2/node_modules/async/dist/async.js:76:12
4|mymicds  |     at portal.getDayRotation (/home/node/MyMICDS/MyMICDS-v2/src/libs/schedule.js:268:8)
4|mymicds  |     at Request.request [as _callback] (/home/node/MyMICDS/MyMICDS-v2/src/libs/portal.js:313:6)
```

**Comment by iProdigy** [comment]
https://github.com/michaelgira23/MyMICDS-v2/blob/master/src/libs/schedule.js#L289

The variable blocks is never defined.
